"use client";
import { useEffect, useState } from 'react';
import { Sprout, RefreshCw, FileText, ScanLine, Target, ShieldCheck, ArrowUpRight, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { CONTRACT, parseCampaign, type LiveCampaign } from '@/lib/live-campaign';
import { WalletActions } from '@/components/wallet-actions';
export default function Home() {
 const [address,setAddress]=useState<string>(CONTRACT);
 useEffect(()=>{const a=new URLSearchParams(location.search).get('contract');if(a&&/^0x[0-9a-fA-F]{40}$/.test(a))setAddress(a);},[]);
 function selectAddress(a:string){setCampaign(null);setAddress(a);const url=new URL(location.href);url.searchParams.set('contract',a);history.replaceState(null,'',url);}
 const [campaign,setCampaign]=useState<LiveCampaign|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!address){setLoading(false);setCampaign(null);return;}const c=new AbortController();setLoading(true);setError('');fetch('/api/campaign?address='+encodeURIComponent(address),{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Could not read Studio Next. Retry or open the contract in the explorer.');return r.json();}).then(data=>{setCampaign(parseCampaign(data));setUpdated(new Date().toLocaleTimeString('en-US'));}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'Unable to read campaign.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh,address]);
 return <div className="app-shell live-page"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Sprout size={23}/></span>fairdrop</a><span className="top-note">GenLayer Studio Next</span><a href="/demo">Sandbox demo</a></header><main>
 <div className="page-heading"><div><p className="eyebrow"><Sparkles size={16}/> COMMUNITY CONTRIBUTIONS</p><h1>Good work deserves <span>recognition.</span></h1><p className="muted">Campaign results, AI reviews, and owner-approved point allocations.</p></div><Button variant="outline" disabled={loading} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={18} className={loading?"spin":""}/>{loading?'Loading…':'Refresh'}</Button></div>
 {error&&<div className="notice" role="alert">{error}{campaign&&' Showing the last successful read; data may be outdated.'}</div>}{loading&&!campaign&&<p role="status">Reading campaign from GenLayer…</p>}
 <WalletActions address={address} campaign={campaign} onAddress={selectAddress} onRefresh={()=>setRefresh(n=>n+1)}/>
 {!address&&<p className="notice">Create a campaign on Studio Next to get started, or open a shared campaign link.</p>}{address&&<div className="demo-banner"><span><strong>Live contract · OKX workspace</strong><br/><a className="contract-address" href={`https://explorer-studio-dev.genlayer.com/address/${address}`} target="_blank" rel="noreferrer">{address} ↗</a><br/>Latest non-final state · May change until finalized · No reward tokens transferred</span></div>}

 {campaign&&<><section className="campaign-card"><div className="campaign-main"><div className="row"><span className={"badge phase-"+campaign.phase}><ShieldCheck size={15}/>{campaign.phase}</span><span className="meta">Rubric v{campaign.rubric_version}</span></div><h2>{campaign.title}</h2><p>{campaign.brief}</p><p>{campaign.phase==='approved'?'This campaign is complete. Explore its reviews and approved allocation below.':'Contribute to this campaign or connect the owner wallet to manage reviews.'}</p><a href="https://studio-next.genlayer.com" target="_blank" rel="noreferrer">Open in Studio ↗</a></div><div className="pool"><span className="eyebrow">CAMPAIGN POOL</span><div>{campaign.pool.toLocaleString('en-US')}<span>points</span></div><p>No tokens transferred</p></div></section>
 <div className="stats"><div><FileText/><span>Submissions<strong>{campaign.entries.length}</strong></span></div><div><ScanLine/><span>Reviewed<strong>{campaign.entries.filter(e=>e.review).length}</strong></span></div><div><Target/><span>Quality threshold<strong>{campaign.threshold}<small> / 100</small></strong></span></div><div><ShieldCheck/><span>Decision<strong className="small-stat">{campaign.phase}</strong></span></div></div>
 <div className="workspace"><section className="work-panel"><Tabs defaultValue="submissions"><TabsList className="view-tabs" variant="line"><TabsTrigger value="submissions">Submissions</TabsTrigger><TabsTrigger value="allocation">Allocation</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList>
 <TabsContent value="submissions"><div className="live-content">{!campaign.entries.length&&<p>No submissions yet.</p>}{campaign.entries.map(e=><article className="live-entry" key={e.id}><div className="entry-title"><span className="entry-symbol"><FileText size={22}/></span><h3>{e.title}</h3></div><p className="contract-address muted">{e.id}</p>{e.withdrawn&&<p>Withdrawn from allocation</p>}<p className="article-body">{e.body}</p>{e.review?<><div className="score-summary"><span><Sparkles size={20}/>AI review</span><strong>{e.review.scores.reduce((a,b)=>a+b,0)}<small> / 100</small></strong><span>{e.review.needs_review?"Manual review required":"Review complete"}</span></div><details open><summary>Review reasons and evidence</summary>{e.review.scores.map((s,i)=><div className="live-reason" key={i}><strong>{['Accuracy','Brief fulfillment','Clarity'][i]} · {s}/{campaign.weights[i]}</strong><div className={"score-track track-"+i}><span style={{width:`${s/campaign.weights[i]*100}%`}}/></div><p>{e.review!.reasons[i]}</p></div>)}<h3>Evidence from the submission</h3>{e.review.evidence.map((q,i)=><blockquote key={i}>{q}</blockquote>)}</details></>:<p>Awaiting evaluation</p>}</article>)}</div></TabsContent>
 <TabsContent value="allocation"><div className="live-content"><h3>{campaign.phase==='approved'?'Approved allocation':'Recorded allocation'}</h3><p className="muted">Values stored by the contract. Minimum qualifying score: {campaign.threshold}/100.</p>{Object.entries(campaign.allocations).length?Object.entries(campaign.allocations).map(([a,p])=><div className="live-allocation" key={a}><span className="contract-address">{a}</span><strong>{p.toLocaleString('en-US')} points</strong></div>):<p>No allocation has been approved.</p>}</div></TabsContent>
 <TabsContent value="history"><ol className="history">{campaign.audit.map((line,i)=><li key={i}><span>{i+1}</span>{line}</li>)}</ol></TabsContent></Tabs></section>
 <aside className="criteria"><p className="eyebrow">PUBLIC CRITERIA</p><h3>One shared rubric.</h3>{['Accuracy','Brief fulfillment','Clarity'].map((label,i)=><div className="criterion" key={label}><div><strong>{label}</strong><b>{campaign.weights[i]}%</b></div><div className={"score-track track-"+i}><span style={{width:`${campaign.weights[i]}%`}}/></div></div>)}<details><summary>Reference material</summary><p className="reference">{campaign.reference}</p></details><p className="muted">Campaign owner</p><p className="contract-address">{campaign.owner}</p></aside></div></>}
 <footer><span>FairDrop · AI Governance</span><span>{updated?`Last successful read: ${updated}`:'No successful read yet'}</span></footer></main></div>;
}
