"use client";
import { useEffect, useRef, useState } from 'react';
import { createClient } from 'genlayer-js';
import { testnetBradbury } from 'genlayer-js/chains';
import type { TransactionHash } from 'genlayer-js/types';
import { Plus, Wallet, Rocket, ArrowUpRight, LoaderCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { type LiveCampaign } from '@/lib/live-campaign';
import defaults from '@/contracts/deploy-args.json';

type Provider = NonNullable<Parameters<typeof createClient>[0]>['provider'];
type WalletProvider = NonNullable<Provider> & {on?:(name:string,fn:()=>void)=>void;removeListener?:(name:string,fn:()=>void)=>void};
type Pending={hash:string;deploy:boolean};
export function WalletActions({address,campaign,onAddress,onRefresh}:{address:string;campaign:LiveCampaign|null;onAddress:(a:string)=>void;onRefresh:()=>void}) {
 const [createOpen,setCreateOpen]=useState(false);
 const provider=useRef<WalletProvider|null>(null),lock=useRef(false);
 const [account,setAccount]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState<Pending|null>(null);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('fairdrop-pending')||'null');if(p&&/^0x[0-9a-fA-F]{64}$/.test(p.hash)&&typeof p.deploy==='boolean')setPending(p);}catch{}},[]);
 useEffect(()=>{const p=provider.current;if(!p)return;const reset=()=>setAccount('');p.on?.('accountsChanged',reset);p.on?.('chainChanged',reset);return()=>{p.removeListener?.('accountsChanged',reset);p.removeListener?.('chainChanged',reset);};},[account]);
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Wallet request failed.');}finally{lock.current=false;setBusy(false);}}
 async function connect(){const p=(window as unknown as {okxwallet?:WalletProvider}).okxwallet;if(!p)throw new Error('OKX Wallet was not detected. Open this page in the browser where OKX is installed.');provider.current=p;const accounts=await p.request({method:'eth_requestAccounts'}) as string[];if(!accounts[0])throw new Error('No wallet account selected.');const chainId='0x'+testnetBradbury.id.toString(16);if(await p.request({method:'eth_chainId'})!==chainId){try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId,chainName:testnetBradbury.name,rpcUrls:[...testnetBradbury.rpcUrls.default.http],nativeCurrency:testnetBradbury.nativeCurrency,blockExplorerUrls:[testnetBradbury.blockExplorers!.default.url]}]});await p.request({method:'wallet_switchEthereumChain',params:[{chainId}]});}}if(await p.request({method:'eth_chainId'})!==chainId)throw new Error('Switch to Bradbury before continuing.');setAccount(accounts[0]);setMessage('OKX connected. Review each transaction in your wallet.');}
 async function wallet(){const p=provider.current;if(!p||!account)throw new Error('Connect OKX first.');const accounts=await p.request({method:'eth_accounts'}) as string[];if(accounts[0]?.toLowerCase()!==account.toLowerCase())throw new Error('Wallet account changed. Reconnect OKX.');if(await p.request({method:'eth_chainId'})!=='0x'+testnetBradbury.id.toString(16))throw new Error('Wallet network changed. Reconnect OKX.');return createClient({chain:testnetBradbury,provider:p,account:account as `0x${string}`});}
 function remember(hash:string,deploy:boolean){const p={hash,deploy};setPending(p);if(deploy)setCreateOpen(false);try{localStorage.setItem('fairdrop-pending',JSON.stringify(p));}catch{}setMessage('Transaction submitted. Check its result below before sending another transaction.');}
 async function check(){if(!pending)return;const tx=await createClient({chain:testnetBradbury}).getTransaction({hash:pending.hash as TransactionHash});const status=String(tx.statusName||tx.status);const success=['ACCEPTED','FINALIZED'].includes(status)&&tx.txExecutionResultName==='FINISHED_WITH_RETURN';setMessage(`${status} · ${tx.txExecutionResultName||'Execution pending'}. ${status==='ACCEPTED'?'Not finalized yet.':''}`);if(success){if(pending.deploy&&tx.recipient)onAddress(tx.recipient);else onRefresh();}if(success||['FINALIZED','CANCELED','UNDETERMINED'].includes(status)||tx.txExecutionResultName==='FINISHED_WITH_ERROR'){setPending(null);try{localStorage.removeItem('fairdrop-pending');}catch{}}}
 async function deploy(form:FormData){const title=String(form.get('title')||'').trim(),brief=String(form.get('brief')||'').trim(),reference=String(form.get('reference')||'').trim(),pool=Number(form.get('pool'));if(!title||!brief||!reference||title.length>120||brief.length>2000||reference.length>12000||!Number.isInteger(pool)||pool<1||pool>1000000)throw new Error('Complete all campaign fields. Pool must be 1–1,000,000 points.');const client=await wallet();const response=await fetch('/fairdrop.py');if(!response.ok)throw new Error('Contract source could not be loaded.');setMessage('Confirm campaign deployment in OKX.');remember(await client.deployContract({code:await response.text(),args:[title,brief,reference,pool]}),true);}
 async function write(method:string,args:string[]=[]){const client=await wallet();setMessage('Confirm transaction in OKX.');remember(await client.writeContract({address:address as `0x${string}`,functionName:method,args,value:BigInt(0)}),false);}
 const owner=!!account&&account.toLowerCase()===campaign?.owner.toLowerCase();const disabled=busy||!!pending||!account;
 return <section className="wallet-panel"><div className="action-intro"><span className="action-icon"><Rocket size={24}/></span><div><h2>Give great contributions a place to grow.</h2><p className="muted">Set your criteria. Let AI review. You make the final decision.</p></div></div><div className="wallet-buttons"><Button variant="outline" disabled={busy} onClick={()=>run(connect)}><Wallet size={18}/>{account?`${account.slice(0,6)}…${account.slice(-4)}`:'Connect OKX'}</Button><Button className="create-primary" onClick={()=>setCreateOpen(true)}><Plus size={20}/>Create campaign</Button></div>
 {message&&<p className="notice" role="status">{message}</p>}{pending&&<div className="pending-transaction"><p className="contract-address">Transaction: {pending.hash}</p><Button disabled={busy} onClick={()=>run(check)}>Check transaction result</Button></div>}
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="create-dialog"><div className="dialog-kicker"><Rocket size={20}/> START SOMETHING VALUABLE</div><DialogTitle className="create-title">Create a campaign</DialogTitle><DialogDescription className="create-description">Define what a great contribution looks like. Your brief and reference are locked when the campaign is deployed.</DialogDescription><form className="form-stack" action={f=>run(()=>deploy(f))}><div className="form-two"><label>Campaign name<Input name="title" defaultValue={String(defaults[0])} maxLength={120} required/></label><label>Reward pool · points<Input name="pool" type="number" min={1} max={1000000} step={1} defaultValue={1000} required/></label></div><label>What should contributors create?<Textarea name="brief" defaultValue={String(defaults[1])} maxLength={2000} rows={3} required/><span className="field-help">Describe the task, audience, and expected outcome.</span></label><label>Reference material<Textarea name="reference" defaultValue={String(defaults[2])} maxLength={12000} rows={5} required/><span className="field-help">AI reviews will check submissions against this source.</span></label><div className="rubric-preview"><span>Accuracy <b>50%</b></span><span>Fulfillment <b>30%</b></span><span>Clarity <b>20%</b></span></div><p className="field-help">Bradbury testnet · Points are not GEN. Review transaction fees in OKX before signing.</p>{message&&<p role="status" className="notice">{message}</p>}<div className="dialog-actions">{!account&&<Button type="button" variant="outline" disabled={busy} onClick={()=>run(connect)}><Wallet size={18}/>Connect OKX</Button>}<Button disabled={disabled} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:<Rocket size={18}/>}Deploy campaign</Button></div>{!account&&<p className="field-help">Connect your wallet to deploy. You can review the form first.</p>}{pending&&<p className="field-help">A transaction is pending. Close this form and check its result before deploying another campaign.</p>}</form></DialogContent></Dialog>
 {campaign?.phase==='open'&&<details className="submit-panel" open><summary><ArrowUpRight size={18}/>Submit a contribution</summary><form className="form-stack" action={f=>run(async()=>{const title=String(f.get('title')||'').trim(),body=String(f.get('body')||'').trim();if(!title||body.length<50||body.length>12000)throw new Error('Add a title and 50–12,000 characters of content.');await write('submit',[title,body]);})}><label>Article title<Input name="title" maxLength={120} required/></label><label>Article content<Textarea name="body" rows={6} placeholder="Write your explanation here. Include a practical example and relevant limitations; do not paste the campaign instructions." minLength={50} maxLength={12000} required/></label><Button disabled={disabled||campaign.entries.some(e=>e.id.toLowerCase()===account.toLowerCase())} type="submit">Submit with OKX</Button><p className="muted">One contribution per wallet.</p></form></details>}
 {owner&&campaign?.phase==='open'&&<Button disabled={disabled||!campaign.entries.length} onClick={()=>run(()=>write('close_submissions'))}>Close submissions and start review</Button>}
 {owner&&campaign?.phase==='review'&&<div>{campaign.entries.some(e=>!e.withdrawn&&e.review?.needs_review)&&<p className="notice" role="status">An AI review is unresolved. Read its reasons and evidence below. Approval is blocked until the author withdraws that unresolved submission in GenLayer Studio, or the owner cancels the campaign there.</p>}{campaign.entries.filter(e=>!e.withdrawn&&!e.review).map(e=><Button key={e.id} disabled={disabled} onClick={()=>run(()=>write('evaluate',[e.id]))}>Evaluate: {e.title}</Button>)}<Button disabled={disabled||campaign.entries.some(e=>!e.withdrawn&&(!e.review||e.review.needs_review))} onClick={()=>run(()=>write('approve'))}>Approve point allocation</Button></div>}
 </section>;
}


