export type Entry={id:string;title:string;author:string;body:string;scores:[number,number,number]|null;reasons:string[];sample:boolean};
export type Campaign={version:1;title:string;brief:string;reference:string;pool:number;threshold:number;entries:Entry[];approved:boolean;log:string[]};
export function allocate(entries:Entry[],pool:number,threshold:number):Record<string,number>{
 if(!Number.isSafeInteger(pool)||pool<0||pool>1000000)throw new Error("Invalid pool");
 const rows=entries.filter(e=>e.scores!==null).map(e=>({id:e.id,score:e.scores!.reduce((a,b)=>a+b,0)})).filter(e=>e.score>=threshold&&e.score>0);
 const total=rows.reduce((s,r)=>s+r.score,0);if(!total)return {};
 const result:Record<string,number>={};let used=0;rows.forEach(r=>{result[r.id]=Math.floor(pool*r.score/total);used+=result[r.id]});
 rows.sort((a,b)=>(pool*b.score%total)-(pool*a.score%total)||(a.id<b.id?-1:a.id>b.id?1:0));for(let i=0;i<pool-used;i++)result[rows[i].id]++;return result;
}
export const initialCampaign:Campaign={version:1,title:"Explain GenLayer to beginners",brief:"Explain Intelligent Contracts with a practical example and relevant limitations. Focus on accuracy and clarity for newcomers.",reference:"GenLayer supports Python Intelligent Contracts that can use LLMs and access the web inside non-deterministic blocks. Validators independently verify results under the Equivalence Principle. Consensus does not guarantee absolute truth; source quality and evaluation criteria affect outcomes. Reference: docs.genlayer.com.",pool:1000,threshold:60,approved:false,log:["Loaded three sample submissions and fixture scores. No GenLayer transactions.","Sample campaign created · rubric v1 locked."],entries:[
{id:"sample-1",author:"Minh Anh",title:"Intelligent Contracts, explained with an example",body:"Intelligent Contracts on GenLayer can use LLMs to process natural language and access the web. For example, a community can evaluate contributions against public criteria. Validators independently check results before the network accepts them. Consensus does not guarantee that every conclusion is correct: source quality and well-defined criteria still matter.",scores:[45,27,18],reasons:["Accurately describes the role of LLMs and validators in the sample reference.","Covers the concept, a community example, and limitations.","Short sentences and a logical explanation."],sample:true},
{id:"sample-2",author:"Quang Huy",title:"From smart contracts to AI-powered contracts",body:"GenLayer allows contracts written in Python to use AI to understand text. For example, a contract can read an article and assess whether it meets a brief. Validators verify the result. Outcomes still depend on input quality, so users should consider the reference sources.",scores:[40,23,17],reasons:["The main ideas are correct, but the consensus explanation lacks detail.","Includes a relevant example and a caveat about data quality.","Generally accessible to beginners."],sample:true},
{id:"sample-3",author:"Lan Chi",title:"Is AI on a blockchain always right?",body:"GenLayer can understand every problem using AI. Once the blockchain reaches consensus, its answer is always absolutely correct and sources never need checking. We can use it to automatically evaluate any article without criteria.",scores:[5,10,15],reasons:["The claim that consensus guarantees absolute correctness contradicts the reference.","Lacks a concrete example and misrepresents the role of criteria.","Readable prose does not compensate for factual errors."],sample:true}]};
