"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Check, FileText, Plus, Scale, ShieldCheck, Sprout } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { allocate, type Entry, type Campaign, initialCampaign } from "@/lib/fairdrop";
import { legacyTranslations } from "@/lib/legacy-translations";
import { useFairdropTools } from "@/lib/use-fairdrop-tools";
const fmt = (n: number) => n.toLocaleString("en-US");
export default function Home() {
 const [campaign,setCampaign]=useState<Campaign>(initialCampaign),[ready,setReady]=useState(false),[notice,setNotice]=useState(""),[modal,setModal]=useState<"create"|"submit"|null>(null),[selected,setSelected]=useState<Entry|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem("fairdrop-v1");if(raw){const p=JSON.parse(raw);if(p.version===1&&Array.isArray(p.entries)){
 const tr=(v:string)=>legacyTranslations[v]??v;
 const oldSample=p.title==="Giải thích GenLayer cho người mới";
 if(oldSample){p.title=initialCampaign.title;p.brief=initialCampaign.brief;p.reference=initialCampaign.reference;}
 p.entries=p.entries.map((e:Entry)=>{const sample=initialCampaign.entries.find(x=>x.id===e.id);return e.sample&&sample?{...e,title:sample.title,body:sample.body,reasons:sample.reasons}:e;});
 p.log=p.log.map((line:string)=>tr(line).replace(/^Nhận bài:/,"Submission received:"));
 setCampaign(p);
 }}}catch{setNotice("Could not load saved data. Showing the sample campaign.");}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem("fairdrop-v1",JSON.stringify(campaign));}catch{setNotice("Your browser could not save this campaign. Keep this page open.");}},[campaign,ready]);
 useFairdropTools(campaign,setSelected);
 const allocations=allocate(campaign.entries,campaign.pool,campaign.threshold),evaluated=campaign.entries.filter(e=>e.scores!==null).length,eligible=campaign.entries.filter(e=>e.scores&&e.scores.reduce((a,b)=>a+b,0)>=campaign.threshold).length;
 function add(form:FormData){const title=String(form.get("title")||"").trim();if(modal==="create"){const pool=Number(form.get("pool")),brief=String(form.get("brief")||"").trim(),reference=String(form.get("reference")||"").trim();if(!title||!brief||!reference||!Number.isSafeInteger(pool)||pool<1||pool>1000000)return;setCampaign({version:1,title,brief,reference,pool,threshold:60,entries:[],approved:false,log:["Campaign created · rubric v1 locked."]});}else{if(campaign.approved)return;const author=String(form.get("author")||"").trim(),body=String(form.get("body")||"").trim();if(!title||!author||body.length<50){setNotice("Provide a title, author, and at least 50 characters.");return;}setCampaign(c=>({...c,entries:[...c.entries,{id:crypto.randomUUID(),title,author,body,scores:null,reasons:[],sample:false}],log:[`Submission received: ${title}`,...c.log]}));}setModal(null);setNotice(modal==="create"?"New campaign created in this browser.":"Submission saved. Scoring will be available once GenLayer is connected.");}
 function approve(){if(!campaign.entries.length||evaluated!==campaign.entries.length||campaign.approved)return;setCampaign(c=>({...c,approved:true,log:["Demo administrator approved the point allocation.",...c.log]}));setNotice("Demo allocation approved. No tokens were transferred.");}
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Sprout size={23}/></span>fairdrop<span className="edition">WORKSPACE</span></a><span className="top-note">AI Governance / Agent Tank</span><span className="avatar" aria-label="Demo administrator">FD</span></header><main>
 <div className="breadcrumb">Community <span>/</span> Contribution campaigns</div><div className="page-heading"><div><p className="eyebrow">CONTRIBUTIONS, RECOGNIZED.</p><h1>Real contributions. Fair rewards.</h1><p className="muted">Open criteria. Transparent rewards. Community decisions.</p></div><Button onClick={()=>setModal("create")}><Plus size={17}/>Create campaign</Button></div>
 <div className="demo-banner"><ShieldCheck size={19}/><span><strong>Product prototype</strong> · Sample scores are fixtures, not GenLayer results. Data is saved in this browser only.</span></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss notification">×</button></div>}
 <section className="campaign-card"><div className="campaign-main"><div className="row"><span className="badge">{campaign.approved?"Closed":"Accepting submissions"}</span><span className="meta">Educational content · Rubric v1</span></div><h2>{campaign.title}</h2><p>{campaign.brief}</p><Button variant="outline" disabled={!ready||campaign.approved} onClick={()=>setModal("submit")}>Submit contribution <ArrowUpRight size={17}/></Button></div><div className="pool"><span className="eyebrow">REWARD POOL</span><div>{fmt(campaign.pool)}<span>points</span></div><p>Demo points · not tokens</p><div className="pool-line"/><span>{eligible} submissions eligible for rewards</span></div></section>
 <div className="stats"><div><FileText size={20}/><span>Submissions<strong>{fmt(campaign.entries.length)}</strong></span></div><div><Scale size={20}/><span>Reviewed<strong>{evaluated}<small> / {campaign.entries.length}</small></strong></span></div><div><ShieldCheck size={20}/><span>Quality threshold<strong>{campaign.threshold}<small> / 100</small></strong></span></div><div><Check size={20}/><span>Final decision<strong className="small-stat">{campaign.approved?"Approved":"Awaiting approval"}</strong></span></div></div>
 <div className="workspace"><section className="work-panel"><Tabs defaultValue="submissions"><TabsList variant="line" className="view-tabs"><TabsTrigger value="submissions">Submissions <span className="count">{campaign.entries.length}</span></TabsTrigger><TabsTrigger value="allocation">Reward allocation</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList>
 <TabsContent value="submissions"><div className="section-heading"><div><h3>Community contributions</h3><p className="muted">Explore scores and reasoning for each criterion.</p></div><span className="meta">{campaign.entries.length} submissions</span></div><div className="entries">{campaign.entries.length===0?<div className="empty"><FileText/><h3>No submissions yet</h3><p>Submit an article to get started.</p></div>:campaign.entries.map((e,i)=><button key={e.id} className="entry" onClick={()=>setSelected(e)}><span className={"entry-avatar color-"+i%3}>{e.author.slice(0,2).toUpperCase()}</span><span className="entry-info"><strong>{e.title}</strong><span>{e.author} · {e.sample?"Sample":"New submission"}</span></span><span className="entry-score">{e.scores?e.scores.reduce((a,b)=>a+b,0):"—"}<small>{e.scores?"/ 100":"Unscored"}</small></span><ArrowUpRight size={18}/></button>)}</div></TabsContent>
 <TabsContent value="allocation"><div className="section-heading"><div><h3>{campaign.approved?"Approved allocation":"Proposed allocation"}</h3><p className="muted">Only submissions scoring at least {campaign.threshold} points qualify.</p></div></div>{evaluated!==campaign.entries.length&&<p className="inline-warning">Some submissions are unscored. These amounts are provisional and cannot be approved yet.</p>}<Table><TableHeader><TableRow><TableHead>Contributor</TableHead><TableHead>Quality score</TableHead><TableHead className="text-right">Reward points</TableHead></TableRow></TableHeader><TableBody>{campaign.entries.map(e=><TableRow key={e.id}><TableCell>{e.author}</TableCell><TableCell>{e.scores?e.scores.reduce((a,b)=>a+b,0):"Unscored"}</TableCell><TableCell className="text-right font-semibold">{fmt(allocations[e.id]||0)}</TableCell></TableRow>)}</TableBody></Table><div className="allocation-footer"><p className="muted">{eligible===0?"No submissions qualify. The reward pool remains unallocated.":"Largest-remainder rounding keeps the total equal to the reward pool."}</p><Button disabled={!ready||campaign.approved||!campaign.entries.length||evaluated!==campaign.entries.length} onClick={approve}>{campaign.approved?"Approved":"Approve demo allocation"}</Button></div></TabsContent>
 <TabsContent value="history"><div className="section-heading"><h3>Browser-local history</h3></div><ol className="history">{campaign.log.map((line,i)=><li key={i}><span>{String(campaign.log.length-i).padStart(2,"0")}</span>{line}</li>)}</ol></TabsContent></Tabs></section>
 <aside className="criteria"><span className="eyebrow">PUBLIC FROM THE START</span><h3>One shared rubric.<br/>The same for everyone.</h3>{[["01","Accuracy","50","Ground claims in the reference. Do not invent facts."],["02","Brief fulfillment","30","Explain the concept, give an example, and discuss limitations."],["03","Clarity","20","Clear, well structured, and accessible to beginners."]].map(([n,t,w,d])=><div className="criterion" key={n}><div><span>{n}</span><strong>{t}</strong><b>{w}%</b></div><p>{d}</p></div>)}<div className="human-note"><ShieldCheck size={20}/><p>AI proposes.<br/><strong>The community approves.</strong></p></div><details><summary>Reference material</summary><p className="reference">{campaign.reference}</p></details></aside></div><footer><span>fairdrop <span className="muted">/ Build 01</span></span><span>GenLayer scoring: not connected</span></footer></main>
 <Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="fair-modal"><DialogTitle>{modal==="create"?"Create a new campaign":"Submit contribution"}</DialogTitle><DialogDescription>{modal==="create"?"A new campaign replaces the current browser-local campaign. Rubric weights 50/30/20 and the minimum score of 60 are fixed in this prototype.":"New submissions are saved for scoring after GenLayer is connected. Sample scores will not be used to grade your work."}</DialogDescription><form action={add} className="form-stack"><label>{modal==="create"?"Campaign name":"Article title"}<Input name="title" required maxLength={120}/></label>{modal==="create"?<><label>Demo reward pool<Input name="pool" type="number" min="1" max="1000000" step="1" defaultValue="1000" required/></label><label>Campaign brief<Textarea name="brief" required maxLength={2000}/></label><label>Reference material<Textarea name="reference" required maxLength={12000}/></label></>:<><label>Contributor name<Input name="author" required maxLength={60}/></label><label>Article content<Textarea name="body" required minLength={50} maxLength={12000} rows={8}/></label></>}<Button type="submit">{modal==="create"?"Create campaign":"Save submission"}</Button></form></DialogContent></Dialog>
 <Dialog open={selected!==null} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="fair-modal"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.author} · {selected?.sample?"Sample review, not verified on GenLayer":"No GenLayer review yet"}</DialogDescription><p className="article-body">{selected?.body}</p>{selected?.scores?<div className="score-details">{selected.scores.map((score,i)=><div key={i}><strong>{["Accuracy","Brief fulfillment","Clarity"][i]} <b>{score}/{[50,30,20][i]}</b></strong><p>{selected.reasons[i]}</p></div>)}</div>:<p className="inline-warning">Submission saved. GenLayer integration is in progress; no quality score is available.</p>}</DialogContent></Dialog></div>;
}
